### ISSUE TITLE
New auth theme

### ISSUE THREAD

**Issue by anbraten** [anbraten/obelix#14]
# Add custom auth theme

## TODO
- [x] show oidc "client" name
- [x] show oidc "client" logo
- [x] show oidc "client" description
- [x] test login
- [x] test logout
- [x] test registration & first login flow 
- [x] add required to input fields
- [x] improve alert / message style
- [x] test reset email flow
