### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by anbraten** [anbraten/obelix#21]
# Trainer permissions
- [x] ~~book for different users (booking.trainer=trainer.id)~~ (moved #23)
- [x] ~~remove bookings with booking.trainer=trainer.id~~ (moved #23)
- [x] book 3 weeks from now

# Admin permissions
- [x] access admin area (see #17)
- [x] select user in booking
- [x] ~~booking without date restrictions~~
- [x] remove all bookings (past, user!=admin.id)
