### ISSUE TITLE
Trainer multiple rentables booking

### ISSUE THREAD

**Issue by anbraten** [anbraten/obelix#23]
Trainer should be able to book multiple rentables for one time.

## trainer booking flow
- select date, start, end
- select boats from table (columns: select-checkbox, name, category, bookingInfo)
- select user per boat (or leave empty / trainer name)

## TODO
- [x] select multiples rentables for one booking (add `booking.rentables=[]`)
- [x] show trainer booings with comma separated list of rentables
- [x] ~~select user per rentable in booking~~
- [x] ~~expandable list to view rentables with assigned users~~

**Comment by anbraten** [comment]
Use b-table for rentables list. 
columns: `select--check-box`, `name`, `category`, `bookingInfo`
