### ISSUE TITLE
Page: Bookings list

### ISSUE THREAD

**Issue by anbraten** [anbraten/obelix#3]
## Description
Show all reservations from one day (beginning today).

## Navigation
You can go to previous dates and future dates (max 7 days from today) to see their corresponding reservations on the selected date you can click the "Book a boat" button to start a new reservation. 

## Reservation list
Behind each reservation you created is a "cancel reservation" button

## TODO
- [x] ask to confirm booking cancellation
- [x] improve cancel button style
- [x] sort bookings list
- [x] style bookings list (even space)
- [x] protect future dates (normal user: 7 days, trainer 14 days) 
- [x] remove date from url (stop date switching being tracked by matomo) 
- [x] show more details on click (notes)
- [x] improve date selection
