### ISSUE TITLE
Page: new reservation

### ISSUE THREAD

**Issue by anbraten** [anbraten/obelix#4]
# Steps
1. Select date + time
2. Select Category
3. Select boat
4. add notes & confirm

# Todo
- [x] improve time selection
- [x] only allow future dates
- [x] pre-select date from route
- [x] add start-time < end-time check
- [x] only show available boats
- [x] sort boats by name
- [x] add boat alert (special permission required)
- [x] only allow future times for booking (date  == today => check: time > now)
- [x] ~add boat search~ not needed for now
- [x] ~add boat notes (skulls, ...)~ not needed for now
- [x] ~use cards for category~
